# auto-generated file
add_library(jaudio_NES_internal STATIC
		"src/static/jaudio_NES/internal/aictrl.c"
		"src/static/jaudio_NES/internal/astest.c"
		"src/static/jaudio_NES/internal/audiothread.c"
		"src/static/jaudio_NES/internal/cpubuf.c"
		"src/static/jaudio_NES/internal/dspboot.c"
		"src/static/jaudio_NES/internal/dspbuf.c"
		"src/static/jaudio_NES/internal/dspproc.c"
		"src/static/jaudio_NES/internal/dummyrom.c"
		"src/static/jaudio_NES/internal/dvdthread.c"
		"src/static/jaudio_NES/internal/neosthread.c"
		"src/static/jaudio_NES/internal/os.c"
		"src/static/jaudio_NES/internal/playercall.c"
		"src/static/jaudio_NES/internal/random.c"
		"src/static/jaudio_NES/internal/sample.c"
		"src/static/jaudio_NES/internal/streamctrl.c"
		"src/static/jaudio_NES/internal/sub_sys.c"
		"src/static/jaudio_NES/internal/track.c"
		"src/static/jaudio_NES/internal/aramcall.c"
		"src/static/jaudio_NES/internal/audioconst.c"
		"src/static/jaudio_NES/internal/audiotable.c"
		"src/static/jaudio_NES/internal/audiowork.c"
		"src/static/jaudio_NES/internal/bankdrv.c"
		"src/static/jaudio_NES/internal/bankread.c"
		"src/static/jaudio_NES/internal/centcalc.c"
		"src/static/jaudio_NES/internal/channel.c"
		"src/static/jaudio_NES/internal/cmdstack.c"
		"src/static/jaudio_NES/internal/connect.c"
		"src/static/jaudio_NES/internal/driver.c"
		"src/static/jaudio_NES/internal/driverinterface.c"
		"src/static/jaudio_NES/internal/dsp_cardunlock.c"
		"src/static/jaudio_NES/internal/dsp_GBAKey.c"
		"src/static/jaudio_NES/internal/dspdriver.c"
		"src/static/jaudio_NES/internal/dspinterface.c"
		"src/static/jaudio_NES/internal/effect.c"
		"src/static/jaudio_NES/internal/fat.c"
		"src/static/jaudio_NES/internal/fxinterface.c"
		"src/static/jaudio_NES/internal/heapctrl.c"
		"src/static/jaudio_NES/internal/ipldec.c"
		"src/static/jaudio_NES/internal/ja_calc.c"
		"src/static/jaudio_NES/internal/jammain_2.c"
		"src/static/jaudio_NES/internal/jamosc.c"
		"src/static/jaudio_NES/internal/memory.c"
		"src/static/jaudio_NES/internal/midplay.c"
		"src/static/jaudio_NES/internal/noteon.c"
		"src/static/jaudio_NES/internal/oneshot.c"
		"src/static/jaudio_NES/internal/rate.c"
		"src/static/jaudio_NES/internal/rspsim.c"
		"src/static/jaudio_NES/internal/seqsetup.c"
		"src/static/jaudio_NES/internal/system.c"
		"src/static/jaudio_NES/internal/tables.c"
		"src/static/jaudio_NES/internal/waveread.c")
target_include_directories(jaudio_NES_internal PRIVATE ${INCLUDE})
target_compile_definitions(jaudio_NES_internal PRIVATE ${DEFINES})
target_compile_options(jaudio_NES_internal PRIVATE ${OPTIONS})
