# auto-generated file
add_library(MSL_C.PPCEABI.bare.H STATIC
		"src/static/MSL_C.PPCEABI.bare.H/abort_exit.c"
		"src/static/MSL_C.PPCEABI.bare.H/ansi_files.c"
		"src/static/MSL_C.PPCEABI.bare.H/ansi_fp.c"
		"src/static/MSL_C.PPCEABI.bare.H/arith.c"
		"src/static/MSL_C.PPCEABI.bare.H/buffer_io.c"
		"src/static/MSL_C.PPCEABI.bare.H/ctype.c"
		"src/static/MSL_C.PPCEABI.bare.H/direct_io.c"
		"src/static/MSL_C.PPCEABI.bare.H/e_acos.c"
		"src/static/MSL_C.PPCEABI.bare.H/e_atan2.c"
		"src/static/MSL_C.PPCEABI.bare.H/e_rem_pio2.c"
		"src/static/MSL_C.PPCEABI.bare.H/errno.c"
		"src/static/MSL_C.PPCEABI.bare.H/file_io.c"
		"src/static/MSL_C.PPCEABI.bare.H/FILE_POS.c"
		"src/static/MSL_C.PPCEABI.bare.H/float.c"
		"src/static/MSL_C.PPCEABI.bare.H/k_cos.c"
		"src/static/MSL_C.PPCEABI.bare.H/k_rem_pio2.c"
		"src/static/MSL_C.PPCEABI.bare.H/k_sin.c"
		"src/static/MSL_C.PPCEABI.bare.H/mbstring.c"
		"src/static/MSL_C.PPCEABI.bare.H/mem.c"
		"src/static/MSL_C.PPCEABI.bare.H/mem_funcs.c"
		"src/static/MSL_C.PPCEABI.bare.H/misc_io.c"
		"src/static/MSL_C.PPCEABI.bare.H/printf.c"
		"src/static/MSL_C.PPCEABI.bare.H/rand.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_atan.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_copysign.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_cos.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_floor.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_frexp.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_ldexp.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_modf.c"
		"src/static/MSL_C.PPCEABI.bare.H/s_sin.c"
		"src/static/MSL_C.PPCEABI.bare.H/scanf.c"
		"src/static/MSL_C.PPCEABI.bare.H/string.c"
		"src/static/MSL_C.PPCEABI.bare.H/strtoul.c"
		"src/static/MSL_C.PPCEABI.bare.H/uart_console_io.c"
		"src/static/MSL_C.PPCEABI.bare.H/w_acos.c"
		"src/static/MSL_C.PPCEABI.bare.H/w_atan2.c"
		"src/static/MSL_C.PPCEABI.bare.H/wchar_io.c")
target_include_directories(MSL_C.PPCEABI.bare.H PRIVATE ${INCLUDE})
target_compile_definitions(MSL_C.PPCEABI.bare.H PRIVATE ${DEFINES})
target_compile_options(MSL_C.PPCEABI.bare.H PRIVATE ${OPTIONS})
